### ISSUE TITLE
typo in del_dup()

### ISSUE THREAD

**Issue by DDelphine** [chenzhangyu/Clevel-Hashing#1]
Hi, 

I found something confusing in the else if branch in del_dup():
// 2. Refer to different locations with the same contents
		else if (key_equal{}(**e1**.get_address(my_pool_uuid)->first, **e1**.get_address(my_pool_uuid)->first)){

this doesn't make sense to me, is this a typo? I think one of them should be e2.

**Comment by chenzhangyu** [comment]
Yes, it's a typo. Thanks for your feedback!
